name: Assignment automated tests

on: [push]

jobs:
  no-tests-run:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: "!startsWith(github.event.head_commit.message, 'E:') &&
         !startsWith(github.event.head_commit.message, 'M:')"
    steps:
      - name: No tests run
        run: |
          exit 1

  meets-expectations-no-valgrind:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: "startsWith(github.event.head_commit.message, 'M:')"
    steps:
      - uses: actions/checkout@v2
      - name: Run M Tests
        run: |
          ./test-m no-valgrind

  meets-expectations:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: meets-expectations-no-valgrind
    if: "startsWith(github.event.head_commit.message, 'M:')"
    steps:
      - uses: actions/checkout@v2
      - name: Install Valgrind
        run: |
          sudo apt-get -qq install valgrind
      - name: Run M Tests
        run: |
          ./test-m


  meets-and-exemplary-no-valgrind:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: "startsWith(github.event.head_commit.message, 'E:')"
    steps:
      - uses: actions/checkout@v2
      - name: Run M Tests
        run: |
          ./test-m no-valgrind
          ./test-e no-valgrind

  meets-and-exemplary:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: meets-and-exemplary-no-valgrind
    if: "startsWith(github.event.head_commit.message, 'E:')"
    steps:
      - uses: actions/checkout@v2
      - name: Install Valgrind
        run: |
          sudo apt-get -qq install valgrind
      - name: Run E Tests
        run: |
          ./test-m
          ./test-e
